# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksee_app', '0002_auto_20170918_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='top_name',
            new_name='genre_name',
        ),
    ]
