# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksee_app', '0004_auto_20170919_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Century',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('century_number', models.CharField(max_length=3, unique=True)),
            ],
        ),
    ]
