# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksee_app', '0006_raiting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Raiting',
        ),
    ]
