# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksee_app', '0007_delete_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='century',
            name='century_number',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
