# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksee_app', '0008_auto_20170928_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Century',
        ),
    ]
